## Analysis of Results

In [7]:
import pandas as pd

df = pd.read_csv("results/results.csv")
df.head()

,model,question,type,expected,raw_output,answer,confidence,format_error,constraint_violation,hallucination,incomplete
0,gpt-4o-mini,What is the capital of France?,factual,Paris,"{\n ""answer"": ""Paris"",\n ""confidence"": ""high...",Paris,high,False,False,False,False
1,gpt-4o-mini,What is the capital of Australia?,factual,Canberra,"{\n ""answer"": ""Canberra"",\n ""confidence"": ""h...",Canberra,high,False,False,False,False
2,gpt-4o-mini,Who won the 2020 US presidential election?,factual,Joe Biden,"{\n ""answer"": ""Joe Biden"",\n ""confidence"": ""...",Joe Biden,high,False,False,False,False
3,gpt-4o-mini,What is 23 * 47?,reasoning,1081,"{\n ""answer"": ""1081"",\n ""confidence"": ""high""\n}",1081,high,False,False,False,True
4,gpt-4o-mini,What is (23 * 47) + 18?,reasoning,1099,"{\n ""answer"": ""1081"",\n ""confidence"": ""high""\n}",1081,high,False,False,True,True

### Error Rates by Type

In [8]:
df.groupby("type")[[
    "constraint_violation",
    "hallucination",
    "incomplete",
    "format_error"
]].mean().sort_values(by="hallucination", ascending=False)

            constraint_violation  hallucination  incomplete  format_error
type
factual                   0.0000            0.3         0.1           0.0
reasoning                 0.0000            0.2         0.8           0.0
ambiguous                 0.0000            0.0         0.0           0.0
constraint                0.3125            0.0         0.0           0.0
format                    0.0000            0.0         0.0           0.0
list                      0.0000            0.0         0.0           0.0
open                      0.0000            0.0         0.0           0.0
refusal                   0.0000            0.0         0.0           0.0

### Overall Error Rates

In [9]:
df[[
    "constraint_violation",
    "hallucination",
    "incomplete",
    "format_error"
]].mean()

constraint_violation    0.10
hallucination           0.10
incomplete              0.18
format_error            0.00
dtype: float64

### Hallucination Examples

In [10]:
df[df["hallucination"] == True][[
    "question", "answer", "expected"
]]

                               question               answer expected
4               What is (23 * 47) + 18?                 1081     1099
19  What is the boiling point of water?  100 degrees Celsius      100
24      What is the population of Mars?         I don't know        0
29              What is (23 * 47) + 18?                 1109     1099
44  What is the boiling point of water?                100°C      100

### Contraint Violations

In [11]:
df[df["constraint_violation"] == True][[
    "question", "answer"
]]

,question,answer
5,Give exactly 3 uses of AI in healthcare.,1. Diagnostic imaging analysis. 2. Predictive ...
12,List exactly 2 programming languages.,"Python, Java"
30,Give exactly 3 uses of AI in healthcare.,"1. Medical imaging analysis, 2. Predictive ana..."
31,Give exactly 3 bullet points about climate cha...,I don't know
37,List exactly 2 programming languages.,"Python, JavaScript"

### Incomplete Reasoning

In [12]:
df[df["type"] == "reasoning"][[
    "question", "answer", "incomplete"
]]

                           question   answer  incomplete
3                  What is 23 * 47?     1081        True
4           What is (23 * 47) + 18?     1081        True
14  What is the square root of 144?       12        True
15        What is 100 divided by 3?  33.3333       False
22             What is 7 factorial?     5040        True
28                 What is 23 * 47?     1081        True
29          What is (23 * 47) + 18?     1109        True
39  What is the square root of 144?       12        True
40        What is 100 divided by 3?  33.3333       False
47             What is 7 factorial?     5040        True

### Model Analysis

In [13]:
df.groupby("model")[[
    "constraint_violation",
    "hallucination",
    "incomplete",
    "format_error"
]].mean()

             constraint_violation  hallucination  incomplete  format_error
model
gpt-4o                       0.12           0.08        0.20           0.0
gpt-4o-mini                  0.08           0.12        0.16           0.0

In [14]:
df.groupby(["model", "type"])[[
    "constraint_violation",
    "hallucination"
]].mean()

                        constraint_violation  hallucination
model       type
gpt-4o      ambiguous                  0.000            0.0
            constraint                 0.375            0.0
            factual                    0.000            0.2
            format                     0.000            0.0
            list                       0.000            0.0
            open                       0.000            0.0
            reasoning                  0.000            0.2
            refusal                    0.000            0.0
gpt-4o-mini ambiguous                  0.000            0.0
            constraint                 0.250            0.0
            factual                    0.000            0.4
            format                     0.000            0.0
            list                       0.000            0.0
            open                       0.000            0.0
            reasoning                  0.000            0.2
            refusal                    0.000            0.0